//! The bless step: the vendor's document plus the adopter's Overlay in, one
//! corrected document and two generated Rust files out.
//!
//! ```text
//! cargo run -p xtask -- bless [--spec PATH] [--overlay PATH] [--out DIR]
//! ```
//!
//! What it writes, all committed:
//!
//! - `api-generated/spec/toy.overlaid.yaml` — the corrected document. This is
//!   the single document everything below it is derived from, so none of them
//!   can disagree with it or with each other.
//! - `api-generated/src/types.rs` — `components.schemas` as Rust types, from
//!   typify, with `Money` substituted for the adopter's own newtype.
//! - `api-generated/src/ops.rs` — one typed method per operation, plus the
//!   `(operationId, method, path)` inventory a hand-written operation asserts
//!   against.
//! - `api-generated/src/model.postcard` — the corrected document already
//!   reduced to the facts a command line needs. The CLI loads this instead of
//!   parsing the YAML, and the same reduction is what the two files above were
//!   emitted from, so none of the four can describe a different API.
//!
//! The Overlay is applied with `ErrorOnZeroMatch`, so a correction whose target
//! the vendor has renamed or retyped fails here rather than lapsing quietly.

mod ops;
mod types;

/// What every generated file says at the top: which command wrote it, where a
/// correction belongs instead, and the one exemption generated source gets from
/// this workspace's lints. It is an inner attribute rather than a wrapping
/// module so that the exemption travels with the file it exempts.
const HEADER: &str = "\
//! Generated by `cargo run -p xtask -- bless` from `spec/toy.overlaid.yaml`.
//! Do not edit: every correction belongs in `spec/overlay.yaml`.
#![allow(
    clippy::all,
    clippy::pedantic,
    clippy::restriction,
    missing_debug_implementations,
    unreachable_pub,
    unused,
    rustdoc::all,
    reason = \"generated source is not graded on style; the allow covers this \\
              module and nothing else\"
)]
";

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail, ensure};

fn main() -> Result<()> {
    let mut args = std::env::args().skip(1);
    let task = args.next().unwrap_or_else(|| "bless".to_owned());
    if task != "bless" {
        bail!("unknown task `{task}`; the only task is `bless`");
    }

    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .context("xtask has no parent directory")?
        .to_path_buf();
    let mut spec = root.join("spec/toy.yaml");
    let mut overlay = root.join("spec/overlay.yaml");
    let mut out = root.join("api-generated");

    while let Some(flag) = args.next() {
        let value = args
            .next()
            .with_context(|| format!("{flag} needs a value"))?;
        match flag.as_str() {
            "--spec" => spec = PathBuf::from(value),
            "--overlay" => overlay = PathBuf::from(value),
            "--out" => out = PathBuf::from(value),
            other => bail!("unknown flag `{other}`"),
        }
    }

    let document = read(&spec)?;
    let corrections = read(&overlay)?;

    // One Overlay application, and one reduction, by the crate the CLI links.
    // Both live behind `typed-openapi`'s `document` feature, which this crate
    // is the only member of the workspace to enable — so the CLI cannot make
    // either call, and the reduction the CLI reads is by construction this one.
    let overlaid = typed_openapi::overlay::apply(&document, &corrections)
        .context("applying the Overlay to the vendor's document")?;
    let overlaid_yaml =
        serde_yaml_ng::to_string(&overlaid).context("writing the overlaid document as YAML")?;

    // Refuse to emit against a document this workspace cannot build a CLI from.
    // Everything below trusts that this succeeded.
    let model = typed_openapi::Document::load(&overlaid_yaml, "")
        .context("the overlaid document does not describe a usable CLI")?;
    let api: openapiv3::OpenAPI =
        serde_json::from_value(overlaid).context("the overlaid document is not OpenAPI 3")?;

    write_plain(
        &out.join("spec/toy.overlaid.yaml"),
        &format!("{}{overlaid_yaml}", overlaid_header(&spec, &overlay)),
    )?;
    write_rust(&out.join("src/types.rs"), &types::emit(&api)?)?;
    write_rust(&out.join("src/ops.rs"), &ops::emit(&api, &model)?)?;
    write_model(&out.join("src/model.postcard"), &model)?;
    Ok(())
}

fn overlaid_header(spec: &Path, overlay: &Path) -> String {
    format!(
        "# Generated by `cargo run -p xtask -- bless` from {} and {}.\n\
         # Do not edit: every correction belongs in the Overlay.\n",
        file_name(spec),
        file_name(overlay),
    )
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .unwrap_or(path.as_os_str())
        .to_string_lossy()
        .into_owned()
}

fn read(path: &Path) -> Result<String> {
    std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))
}

fn write_plain(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(path, contents).with_context(|| format!("writing {}", path.display()))?;
    println!("blessed {}", path.display());
    Ok(())
}

/// Write the file, then hand it to rustfmt, so what lands in the tree is what
/// `cargo fmt --check` expects and the bless step stays one command.
/// Write the reduction the CLI loads, after reading it straight back.
///
/// `model` is the one `Document::load` this step makes — the same value the
/// generated types and wrappers were emitted from — so encoding it is the only
/// way the blob and the document can come apart. The read-back proves they have
/// not: what a binary will deserialise is what this step reduced. `api`'s test
/// suite makes the same comparison against the committed pair, for the case
/// where the bless step was not run at all.
fn write_model(path: &Path, model: &typed_openapi::Document) -> Result<()> {
    let blob = model.to_blob().context("encoding the reduced model")?;
    let read_back =
        typed_openapi::Document::from_blob(&blob).context("reading the reduced model back")?;
    ensure!(
        &read_back == model,
        "the reduced model is not the document's reduction after a round trip"
    );
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(path, &blob).with_context(|| format!("writing {}", path.display()))?;
    println!("blessed {} ({} bytes)", path.display(), blob.len());
    Ok(())
}

fn write_rust(path: &Path, source: &str) -> Result<()> {
    write_plain(path, source)?;
    let status = std::process::Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .arg(path)
        .status()
        .with_context(|| format!("running rustfmt on {}", path.display()))?;
    if !status.success() {
        bail!("rustfmt failed on {}", path.display());
    }
    Ok(())
}
