//! This adoption's own prose about how big its API is, held to the reduction
//! that settles it.
//!
//! Every adoption writes a sentence like the one in `README.md`, and the
//! sentence is true the day it is written. What makes it stay true is not care:
//! it is a test that builds the sentence out of the measurement and fails when
//! the document moves. An Overlay that adds an operation, a vendor revision
//! that withdraws one, a gate renamed — each one reaches the prose here rather
//! than sitting in it unnoticed.

#![expect(
    clippy::expect_used,
    reason = "a test that cannot build its fixture should fail loudly and name it"
)]

use api::Api;
use typed_openapi::Summary;

/// The page a reader arrives at, read at compile time so that a paragraph
/// deleted from it is a failure here rather than a silence.
const README: &str = include_str!("../../README.md");

fn summary() -> Summary {
    Api::new()
        .expect("the embedded model loads")
        .document()
        .summary()
}

/// Every count `README.md` states, built from the measurement and looked for in
/// the page. A number that has moved fails here, naming the phrase to rewrite.
#[test]
fn every_count_the_readme_states_is_the_reductions_own() {
    let summary = summary();
    let behind_each = summary.behind("enshrine");
    assert_eq!(
        behind_each,
        summary.behind("email"),
        "the paragraph says `behind each`, which is one number for both gates"
    );

    let claims = [
        format!("**{} operations**", summary.operations()),
        format!("**{} groups**", summary.groups().len()),
        format!("**{} reads** sent on", summary.reads()),
        format!("**{} writes** held behind", summary.writes()),
        format!("**{} gates**", summary.gates().len()),
        format!("**{behind_each} operation** behind each"),
        format!(
            "**{} operations** are asked for no body",
            summary.bodiless()
        ),
        format!("**{} bodies** go out whole", summary.whole_bodies()),
        format!(
            "**{} parameters** are carried without a flag",
            summary.unreachable().len()
        ),
    ];

    for claim in claims {
        assert!(
            README.contains(&claim),
            "the README does not say `{claim}`; the reduction moved and the \
             paragraph did not"
        );
    }
}

/// The gates are named in the prose as well as counted, and the words are the
/// document's. A gate an Overlay renames stops being on the page.
#[test]
fn every_gate_the_readme_names_is_one_the_document_names() {
    let summary = summary();
    for gate in summary.gates().keys() {
        let named = format!("`--{gate}`");
        assert!(
            README.contains(&named),
            "the README does not name the gate {named}"
        );
    }
}

/// The committed page and the committed blob are two artefacts of one bless
/// run, so the page has to be what the blob counts. A page committed without
/// the model beside it — a half-finished bless, a hand-edited number — is this
/// assertion, and it bites without re-running the generator.
#[test]
fn the_committed_page_is_the_committed_models_count() {
    assert!(
        api::SUMMARY.ends_with(&summary().to_string()),
        "the committed summary page is not the embedded model's count — \
         re-run the bless step"
    );
}

/// The page says what it was counted from and what counts it again, which is
/// what makes its numbers measurements rather than a table somebody typed. A
/// reader who cannot tell those apart will either trust a stale number or
/// "correct" a true one.
#[test]
fn the_committed_page_says_where_its_numbers_came_from() {
    let header = api::SUMMARY
        .split("-->")
        .next()
        .expect("the page opens with its provenance");
    assert!(
        header.contains("Generated by `cargo run -p xtask -- bless`"),
        "the page does not name the command that counts it again:\n{header}"
    );
    for input in ["toy.yaml", "corrections.yaml", "cli.yaml"] {
        assert!(
            header.contains(input),
            "the page does not name {input}, which it was counted from:\n{header}"
        );
    }
}
