//! Generated by `cargo run -p xtask -- bless` from `spec/toy.overlaid.yaml`.
//! Do not edit: every correction belongs in `spec/corrections.yaml` and `spec/cli.yaml`.
#![allow(
    clippy::all,
    clippy::pedantic,
    clippy::restriction,
    missing_debug_implementations,
    unreachable_pub,
    unused,
    rustdoc::all,
    reason = "generated source is not graded on style; the allow covers this \
              module and nothing else"
)]
use typed_openapi::{Part, Values};

use crate::{Api, Call, Error, NoContent};
///Every operation the overlaid document declares, in its order.
///
///A wrapper names one of these rather than a string, so the
///wrappers cannot ask for an operation the document lacks; and
///`Api::new` pairs the whole set with the embedded document
///once, so a stale artefact is a named error at startup rather
///than a subcommand that cannot run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OperationId {
    ///listVouchers
    ListVouchers,
    ///createVoucher
    CreateVoucher,
    ///getVoucher
    GetVoucher,
    ///updateVoucher
    UpdateVoucher,
    ///enshrineVoucher
    EnshrineVoucher,
    ///renderVoucher
    RenderVoucher,
    ///sendVoucherByEmail
    SendVoucherByEmail,
    ///createContact
    CreateContact,
    ///uploadDocument
    UploadDocument,
    ///uploadDocumentMultipart
    UploadDocumentMultipart,
    ///archiveVoucher
    ArchiveVoucher,
}
impl OperationId {
    ///Every variant, in the document's order — which is also
    ///`OPERATIONS`' order and this enum's discriminant order.
    pub const ALL: &'static [OperationId] = &[
        OperationId::ListVouchers,
        OperationId::CreateVoucher,
        OperationId::GetVoucher,
        OperationId::UpdateVoucher,
        OperationId::EnshrineVoucher,
        OperationId::RenderVoucher,
        OperationId::SendVoucherByEmail,
        OperationId::CreateContact,
        OperationId::UploadDocument,
        OperationId::UploadDocumentMultipart,
        OperationId::ArchiveVoucher,
    ];
    ///The `<group> <command>` pair the CLI mounts this
    ///operation under.
    ///
    ///This is the one place a name off the command line becomes
    ///a typed operation; everything past it is exhaustive.
    #[must_use]
    pub fn from_command(group: &str, command: &str) -> Option<Self> {
        match (group, command) {
            ("vouchers", "list") => Some(Self::ListVouchers),
            ("vouchers", "create") => Some(Self::CreateVoucher),
            ("vouchers", "get") => Some(Self::GetVoucher),
            ("vouchers", "update") => Some(Self::UpdateVoucher),
            ("vouchers", "enshrine") => Some(Self::EnshrineVoucher),
            ("vouchers", "render") => Some(Self::RenderVoucher),
            ("vouchers", "send-by-email") => Some(Self::SendVoucherByEmail),
            ("contacts", "create") => Some(Self::CreateContact),
            ("documents", "create") => Some(Self::UploadDocument),
            ("documents-multipart", "create") => Some(Self::UploadDocumentMultipart),
            ("vouchers", "archive") => Some(Self::ArchiveVoucher),
            _ => None,
        }
    }
    ///Does `body` fit the type this operation's wrapper takes?
    ///
    ///An operation whose body this crate has no type for accepts
    ///anything, which is the document's own position on it.
    pub fn check_body(
        self,
        body: &serde_json::Value,
    ) -> Result<(), typed_openapi::client::BodyError> {
        match self {
            Self::CreateVoucher => {
                typed_openapi::client::fits::<crate::types::Voucher>("createVoucher", body)
            }
            Self::UpdateVoucher => {
                typed_openapi::client::fits::<crate::types::Voucher>("updateVoucher", body)
            }
            Self::SendVoucherByEmail => {
                typed_openapi::client::fits::<crate::types::Delivery>("sendVoucherByEmail", body)
            }
            Self::CreateContact => {
                typed_openapi::client::fits::<crate::types::Contact>("createContact", body)
            }
            Self::ListVouchers
            | Self::GetVoucher
            | Self::EnshrineVoucher
            | Self::RenderVoucher
            | Self::UploadDocument
            | Self::UploadDocumentMultipart
            | Self::ArchiveVoucher => Ok(()),
        }
    }
}
///Every `(operationId, method, path)` the overlaid document declares.
///
///Row `n` describes `OperationId::ALL[n]`. `Api::new` checks that
///against the document it embeds before handing out an `Api`.
pub const OPERATIONS: &[(&str, &str, &str)] = &[
    ("listVouchers", "GET", "/vouchers"),
    ("createVoucher", "POST", "/vouchers"),
    ("getVoucher", "GET", "/vouchers/{id}"),
    ("updateVoucher", "PUT", "/vouchers/{id}"),
    ("enshrineVoucher", "POST", "/vouchers/{id}/enshrine"),
    ("renderVoucher", "GET", "/vouchers/{id}/render"),
    ("sendVoucherByEmail", "POST", "/vouchers/{id}/send-by-email"),
    ("createContact", "POST", "/contacts"),
    ("uploadDocument", "POST", "/documents"),
    ("uploadDocumentMultipart", "POST", "/documents-multipart"),
    ("archiveVoucher", "POST", "/vouchers/{id}/archive"),
];
///How many operations the document declares. An operation *added*
///upstream moves this number and nothing else would have noticed.
pub const OPERATION_COUNT: usize = 11usize;
const fn str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}
///`const _: () = assert!(documented(..));` beside a hand-written
///operation, or beside code that depends on one, turns that
///operation's disappearance from the document into a compile error.
#[must_use]
pub const fn documented(id: &str, method: &str, path: &str) -> bool {
    let mut i = 0;
    while i < OPERATIONS.len() {
        let (oid, m, p) = OPERATIONS[i];
        if str_eq(oid, id) && str_eq(m, method) && str_eq(p, path) {
            return true;
        }
        i += 1;
    }
    false
}
impl Api {
    /**
    List vouchers

    GET /vouchers

    A read.
    */
    pub fn list_vouchers(
        &self,
        status: Option<crate::types::VoucherStatus>,
        limit: Option<i64>,
        r#type: Option<&str>,
    ) -> Result<Call<'_, Vec<crate::types::Voucher>>, Error> {
        self.call(
            OperationId::ListVouchers,
            Values::new()
                .maybe("status", status)
                .maybe("limit", limit)
                .maybe("type", r#type),
        )
    }
    /**
    Create a voucher

    POST /vouchers

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit`.
    */
    pub fn create_voucher(
        &self,
        body: &crate::types::Voucher,
    ) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.call(
            OperationId::CreateVoucher,
            Values::new().json(crate::to_json(body)?),
        )
    }
    /**
    Fetch one voucher

    GET /vouchers/{id}

    A read.
    */
    pub fn get_voucher(&self, id: i64) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.call(OperationId::GetVoucher, Values::new().param("id", id))
    }
    /**
    Replace a voucher

    PUT /vouchers/{id}

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit`.
    */
    pub fn update_voucher(
        &self,
        id: i64,
        body: &crate::types::Voucher,
    ) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.call(
            OperationId::UpdateVoucher,
            Values::new().param("id", id).json(crate::to_json(body)?),
        )
    }
    /**
    Finalize a voucher (irreversible)

    POST /vouchers/{id}/enshrine

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit` and `--enshrine`.
    */
    pub fn enshrine_voucher(&self, id: i64) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.call(OperationId::EnshrineVoucher, Values::new().param("id", id))
    }
    /**
    Render the voucher to PDF and store it on the server (this GET writes)

    GET /vouchers/{id}/render

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit`.
    */
    pub fn render_voucher(&self, id: i64) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.call(OperationId::RenderVoucher, Values::new().param("id", id))
    }
    /**
    Email the voucher to a recipient

    POST /vouchers/{id}/send-by-email

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit` and `--email`.
    */
    pub fn send_voucher_by_email(
        &self,
        id: i64,
        body: &crate::types::Delivery,
    ) -> Result<Call<'_, NoContent>, Error> {
        self.call(
            OperationId::SendVoucherByEmail,
            Values::new().param("id", id).json(crate::to_json(body)?),
        )
    }
    /**
    Create a contact

    POST /contacts

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit`.
    */
    pub fn create_contact(
        &self,
        body: &crate::types::Contact,
    ) -> Result<Call<'_, crate::types::Contact>, Error> {
        self.call(
            OperationId::CreateContact,
            Values::new().json(crate::to_json(body)?),
        )
    }
    /**
    Upload a document as a PDF

    POST /documents

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit`.

    `body` is sent verbatim under the document's own `application/pdf`, which this crate does not assemble.
    */
    pub fn upload_document(&self, body: Vec<u8>) -> Result<Call<'_, NoContent>, Error> {
        self.call(OperationId::UploadDocument, Values::new().raw(body))
    }
    /**
    Upload a document as multipart parts

    POST /documents-multipart

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit`.

    `parts` are assembled into a `multipart/form-data` body. The document declares: file.
    */
    pub fn upload_document_multipart(
        &self,
        parts: Vec<Part>,
    ) -> Result<Call<'_, NoContent>, Error> {
        self.call(
            OperationId::UploadDocumentMultipart,
            Values::new().multipart(parts),
        )
    }
    /**
    Archive a voucher (undocumented; vendor ships it)

    POST /vouchers/{id}/archive

    This operation writes. A Rust caller is trusted; the CLI holds it behind `--commit`.
    */
    pub fn archive_voucher(&self, id: i64) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.call(OperationId::ArchiveVoucher, Values::new().param("id", id))
    }
}
#[cfg(feature = "builder")]
#[::typed_openapi::bon::bon(crate = ::typed_openapi::bon)]
impl Api {
    ///The same call as [`Api::list_vouchers`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn list_vouchers_builder(
        &self,
        status: Option<crate::types::VoucherStatus>,
        limit: Option<i64>,
        r#type: Option<&str>,
    ) -> Result<Call<'_, Vec<crate::types::Voucher>>, Error> {
        self.list_vouchers(status, limit, r#type)
    }
    ///The same call as [`Api::create_voucher`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn create_voucher_builder(
        &self,
        body: &crate::types::Voucher,
    ) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.create_voucher(body)
    }
    ///The same call as [`Api::get_voucher`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn get_voucher_builder(&self, id: i64) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.get_voucher(id)
    }
    ///The same call as [`Api::update_voucher`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn update_voucher_builder(
        &self,
        id: i64,
        body: &crate::types::Voucher,
    ) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.update_voucher(id, body)
    }
    ///The same call as [`Api::enshrine_voucher`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn enshrine_voucher_builder(
        &self,
        id: i64,
    ) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.enshrine_voucher(id)
    }
    ///The same call as [`Api::render_voucher`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn render_voucher_builder(
        &self,
        id: i64,
    ) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.render_voucher(id)
    }
    ///The same call as [`Api::send_voucher_by_email`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn send_voucher_by_email_builder(
        &self,
        id: i64,
        body: &crate::types::Delivery,
    ) -> Result<Call<'_, NoContent>, Error> {
        self.send_voucher_by_email(id, body)
    }
    ///The same call as [`Api::create_contact`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn create_contact_builder(
        &self,
        body: &crate::types::Contact,
    ) -> Result<Call<'_, crate::types::Contact>, Error> {
        self.create_contact(body)
    }
    ///The same call as [`Api::upload_document`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn upload_document_builder(&self, body: Vec<u8>) -> Result<Call<'_, NoContent>, Error> {
        self.upload_document(body)
    }
    ///The same call as [`Api::upload_document_multipart`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn upload_document_multipart_builder(
        &self,
        parts: Vec<Part>,
    ) -> Result<Call<'_, NoContent>, Error> {
        self.upload_document_multipart(parts)
    }
    ///The same call as [`Api::archive_voucher`], with its arguments named. A missing required argument is a compile error.
    #[builder]
    pub fn archive_voucher_builder(
        &self,
        id: i64,
    ) -> Result<Call<'_, crate::types::Voucher>, Error> {
        self.archive_voucher(id)
    }
}
