//! Generated by `cargo run -p xtask -- bless` from `spec/toy.overlaid.yaml`.
//! Do not edit: every correction belongs in `spec/corrections.yaml` and `spec/cli.yaml`.
#![allow(
    clippy::all,
    clippy::pedantic,
    clippy::restriction,
    missing_debug_implementations,
    unreachable_pub,
    unused,
    rustdoc::all,
    reason = "generated source is not graded on style; the allow covers this \
              module and nothing else"
)]
///`Settings::replace("money", "money::Money")` promises that this type parses from a string and prints to one, and the newtype above is written in terms of both.
const _: () = {
    fn parses_from_a_string<T: ::std::str::FromStr>() {}
    fn prints_to_a_string<T: ::std::fmt::Display>() {}
    fn a_type_named_by_settings_replace() {
        parses_from_a_string::<money::Money>();
        prints_to_a_string::<money::Money>();
    }
};
///`Address`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct Address {
    pub city: ::std::string::String,
    pub street: ::std::string::String,
}
///`Contact`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct Contact {
    pub address: Address,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub id: ::std::option::Option<i64>,
    pub name: ::std::string::String,
}
///`CreateLedgerEntryBody`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct CreateLedgerEntryBody {
    pub account: LedgerAccount,
    ///Decimal amount as a string
    pub amount: money::Money,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub memo: ::std::option::Option<Memo>,
}
///`CreateLedgerEntryResponse`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, PartialEq)]
pub struct CreateLedgerEntryResponse {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub account: ::std::option::Option<LedgerAccount>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub balance: ::std::option::Option<money::Money>,
}
///An ISO 4217 currency code.
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct Currency(::std::string::String);
impl ::std::ops::Deref for Currency {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<Currency> for ::std::string::String {
    fn from(value: Currency) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for Currency {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::typed_openapi::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::typed_openapi::regress::Regex::new("^[A-Z]{3}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[A-Z]{3}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for Currency {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Currency {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for Currency {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`Delivery`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct Delivery {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<Memo>,
    ///Mailbox the voucher is sent to
    pub recipient: ::std::string::String,
}
///The four-digit account an entry is posted to.
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct LedgerAccount(::std::string::String);
impl ::std::ops::Deref for LedgerAccount {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<LedgerAccount> for ::std::string::String {
    fn from(value: LedgerAccount) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for LedgerAccount {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::typed_openapi::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::typed_openapi::regress::Regex::new("^[0-9]{4}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[0-9]{4}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for LedgerAccount {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for LedgerAccount {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for LedgerAccount {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
/**
A note the sender keeps against the voucher.

The server stores it verbatim and never reads it. Senders paste a
reference in, under a heading of their own:

   PO-1234, approved by finance

and it comes back exactly as it was sent.

*/
#[derive(
    ::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd,
)]
#[serde(transparent)]
pub struct Memo(pub ::std::string::String);
impl ::std::ops::Deref for Memo {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<Memo> for ::std::string::String {
    fn from(value: Memo) -> Self {
        value.0
    }
}
impl ::std::convert::From<::std::string::String> for Memo {
    fn from(value: ::std::string::String) -> Self {
        Self(value)
    }
}
impl ::std::fmt::Display for Memo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
impl ::std::str::FromStr for Memo {
    type Err = ::std::convert::Infallible;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.to_string()))
    }
}
///A decimal amount carried in a string.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(transparent)]
pub struct Money(pub money::Money);
impl ::std::ops::Deref for Money {
    type Target = money::Money;
    fn deref(&self) -> &money::Money {
        &self.0
    }
}
impl ::std::convert::From<Money> for money::Money {
    fn from(value: Money) -> Self {
        value.0
    }
}
impl ::std::convert::From<money::Money> for Money {
    fn from(value: money::Money) -> Self {
        Self(value)
    }
}
impl ::std::fmt::Display for Money {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
impl ::std::str::FromStr for Money {
    type Err = <money::Money as ::std::str::FromStr>::Err;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.parse()?))
    }
}
impl ::std::convert::TryFrom<&str> for Money {
    type Error = <money::Money as ::std::str::FromStr>::Err;
    fn try_from(value: &str) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<String> for Money {
    type Error = <money::Money as ::std::str::FromStr>::Err;
    fn try_from(value: String) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
///`Voucher`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct Voucher {
    pub currency: Currency,
    ///Server-assigned id
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub id: ::std::option::Option<i64>,
    ///Vendor's internal bookkeeping reference (undocumented)
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub internal_ref: ::std::option::Option<::std::string::String>,
    pub status: VoucherStatus,
    pub total: Money,
}
///`VoucherStatus`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum VoucherStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "paid")]
    Paid,
}
impl ::std::fmt::Display for VoucherStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Draft => f.write_str("draft"),
            Self::Open => f.write_str("open"),
            Self::Paid => f.write_str("paid"),
        }
    }
}
impl ::std::str::FromStr for VoucherStatus {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "draft" => Ok(Self::Draft),
            "open" => Ok(Self::Open),
            "paid" => Ok(Self::Paid),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for VoucherStatus {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for VoucherStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
impl ::std::fmt::Display for Currency {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, f)
    }
}
impl ::std::fmt::Display for LedgerAccount {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, f)
    }
}
